

export const aliciKurumlar = [
  {
    id: "alici-adana",
    ad: "Adana Şehir Hastanesi",
    il: "Adana",
    eposta: "adanasehir@saglik.gov.tr",
  },
  {
    id: "alici-adiyaman",
    ad: "Adıyaman Şehir Hastanesi",
    il: "Adıyaman",
    eposta: "adiyamansehir@saglik.gov.tr",
  },
  {
    id: "alici-afyonkarahisar",
    ad: "Afyonkarahisar Şehir Hastanesi",
    il: "Afyonkarahisar",
    eposta: "afyonkarahisarsehir@saglik.gov.tr",
  },
  {
    id: "alici-agri",
    ad: "Ağrı Şehir Hastanesi",
    il: "Ağrı",
    eposta: "agrisehir@saglik.gov.tr",
  },
  {
    id: "alici-amasya",
    ad: "Amasya Şehir Hastanesi",
    il: "Amasya",
    eposta: "amasyasehir@saglik.gov.tr",
  },
  {
    id: "alici-ankara",
    ad: "Ankara Şehir Hastanesi",
    il: "Ankara",
    eposta: "ankarasehir@saglik.gov.tr",
  },
  {
    id: "alici-antalya",
    ad: "Antalya Şehir Hastanesi",
    il: "Antalya",
    eposta: "antalyasehir@saglik.gov.tr",
  },
  {
    id: "alici-artvin",
    ad: "Artvin Şehir Hastanesi",
    il: "Artvin",
    eposta: "artvinsehir@saglik.gov.tr",
  },
  {
    id: "alici-aydin",
    ad: "Aydın Şehir Hastanesi",
    il: "Aydın",
    eposta: "aydinsehir@saglik.gov.tr",
  },
  {
    id: "alici-balikesir",
    ad: "Balıkesir Şehir Hastanesi",
    il: "Balıkesir",
    eposta: "balikesirsehir@saglik.gov.tr",
  },
  {
    id: "alici-bilecik",
    ad: "Bilecik Şehir Hastanesi",
    il: "Bilecik",
    eposta: "bileciksehir@saglik.gov.tr",
  },
  {
    id: "alici-bingol",
    ad: "Bingöl Şehir Hastanesi",
    il: "Bingöl",
    eposta: "bingolsehir@saglik.gov.tr",
  },
  {
    id: "alici-bitlis",
    ad: "Bitlis Şehir Hastanesi",
    il: "Bitlis",
    eposta: "bitlissehir@saglik.gov.tr",
  },
  {
    id: "alici-bolu",
    ad: "Bolu Şehir Hastanesi",
    il: "Bolu",
    eposta: "bolusehir@saglik.gov.tr",
  },
  {
    id: "alici-burdur",
    ad: "Burdur Şehir Hastanesi",
    il: "Burdur",
    eposta: "burdursehir@saglik.gov.tr",
  },
  {
    id: "alici-bursa",
    ad: "Bursa Şehir Hastanesi",
    il: "Bursa",
    eposta: "bursasehir@saglik.gov.tr",
  },
  {
    id: "alici-canakkale",
    ad: "Çanakkale Şehir Hastanesi",
    il: "Çanakkale",
    eposta: "canakkalesehir@saglik.gov.tr",
  },
  {
    id: "alici-cankiri",
    ad: "Çankırı Şehir Hastanesi",
    il: "Çankırı",
    eposta: "cankirisehir@saglik.gov.tr",
  },
  {
    id: "alici-corum",
    ad: "Çorum Şehir Hastanesi",
    il: "Çorum",
    eposta: "corumsehir@saglik.gov.tr",
  },
  {
    id: "alici-denizli",
    ad: "Denizli Şehir Hastanesi",
    il: "Denizli",
    eposta: "denizlisehir@saglik.gov.tr",
  },
  {
    id: "alici-diyarbakir",
    ad: "Diyarbakır Şehir Hastanesi",
    il: "Diyarbakır",
    eposta: "diyarbakirsehir@saglik.gov.tr",
  },
  {
    id: "alici-edirne",
    ad: "Edirne Şehir Hastanesi",
    il: "Edirne",
    eposta: "edirnesehir@saglik.gov.tr",
  },
  {
    id: "alici-elazig",
    ad: "Elazığ Şehir Hastanesi",
    il: "Elazığ",
    eposta: "elazigsehir@saglik.gov.tr",
  },
  {
    id: "alici-erzincan",
    ad: "Erzincan Şehir Hastanesi",
    il: "Erzincan",
    eposta: "erzincansehir@saglik.gov.tr",
  },
  {
    id: "alici-erzurum",
    ad: "Erzurum Şehir Hastanesi",
    il: "Erzurum",
    eposta: "erzurumsehir@saglik.gov.tr",
  },
  {
    id: "alici-eskisehir",
    ad: "Eskişehir Şehir Hastanesi",
    il: "Eskişehir",
    eposta: "eskisehirsehir@saglik.gov.tr",
  },
  {
    id: "alici-gaziantep",
    ad: "Gaziantep Şehir Hastanesi",
    il: "Gaziantep",
    eposta: "gaziantepsehir@saglik.gov.tr",
  },
  {
    id: "alici-giresun",
    ad: "Giresun Şehir Hastanesi",
    il: "Giresun",
    eposta: "giresunsehir@saglik.gov.tr",
  },
  {
    id: "alici-gumushane",
    ad: "Gümüşhane Şehir Hastanesi",
    il: "Gümüşhane",
    eposta: "gumushanesehir@saglik.gov.tr",
  },
  {
    id: "alici-hakkari",
    ad: "Hakkari Şehir Hastanesi",
    il: "Hakkari",
    eposta: "hakkarisehir@saglik.gov.tr",
  },
  {
    id: "alici-hatay",
    ad: "Hatay Şehir Hastanesi",
    il: "Hatay",
    eposta: "hataysehir@saglik.gov.tr",
  },
  {
    id: "alici-isparta",
    ad: "Isparta Şehir Hastanesi",
    il: "Isparta",
    eposta: "ispartasehir@saglik.gov.tr",
  },
  {
    id: "alici-istanbul",
    ad: "İstanbul Şehir Hastanesi",
    il: "İstanbul",
    eposta: "istanbulsehir@saglik.gov.tr",
  },
  {
    id: "alici-izmir",
    ad: "İzmir Şehir Hastanesi",
    il: "İzmir",
    eposta: "izmirsehir@saglik.gov.tr",
  },
  {
    id: "alici-kars",
    ad: "Kars Şehir Hastanesi",
    il: "Kars",
    eposta: "karssehir@saglik.gov.tr",
  },
  {
    id: "alici-kastamonu",
    ad: "Kastamonu Şehir Hastanesi",
    il: "Kastamonu",
    eposta: "kastamonusehir@saglik.gov.tr",
  },
  {
    id: "alici-kayseri",
    ad: "Kayseri Şehir Hastanesi",
    il: "Kayseri",
    eposta: "kayserisehir@saglik.gov.tr",
  },
  {
    id: "alici-kirklareli",
    ad: "Kırklareli Şehir Hastanesi",
    il: "Kırklareli",
    eposta: "kirklarelisehir@saglik.gov.tr",
  },
  {
    id: "alici-kirsehir",
    ad: "Kırşehir Şehir Hastanesi",
    il: "Kırşehir",
    eposta: "kirsehirsehir@saglik.gov.tr",
  },
  {
    id: "alici-kocaeli",
    ad: "Kocaeli Şehir Hastanesi",
    il: "Kocaeli",
    eposta: "kocaelisehir@saglik.gov.tr",
  },
  {
    id: "alici-konya",
    ad: "Konya Şehir Hastanesi",
    il: "Konya",
    eposta: "konyasehir@saglik.gov.tr",
  },
  {
    id: "alici-kutahya",
    ad: "Kütahya Şehir Hastanesi",
    il: "Kütahya",
    eposta: "kutahyasehir@saglik.gov.tr",
  },
  {
    id: "alici-malatya",
    ad: "Malatya Şehir Hastanesi",
    il: "Malatya",
    eposta: "malatyasehir@saglik.gov.tr",
  },
  {
    id: "alici-manisa",
    ad: "Manisa Şehir Hastanesi",
    il: "Manisa",
    eposta: "manisasehir@saglik.gov.tr",
  },
  {
    id: "alici-kahramanmaras",
    ad: "Kahramanmaraş Şehir Hastanesi",
    il: "Kahramanmaraş",
    eposta: "kahramanmarassehir@saglik.gov.tr",
  },
  {
    id: "alici-mardin",
    ad: "Mardin Şehir Hastanesi",
    il: "Mardin",
    eposta: "mardinsehir@saglik.gov.tr",
  },
  {
    id: "alici-mugla",
    ad: "Muğla Şehir Hastanesi",
    il: "Muğla",
    eposta: "muglasehir@saglik.gov.tr",
  },
  {
    id: "alici-mus",
    ad: "Muş Şehir Hastanesi",
    il: "Muş",
    eposta: "mussehir@saglik.gov.tr",
  },
  {
    id: "alici-nevsehir",
    ad: "Nevşehir Şehir Hastanesi",
    il: "Nevşehir",
    eposta: "nevsehirsehir@saglik.gov.tr",
  },
  {
    id: "alici-nigde",
    ad: "Niğde Şehir Hastanesi",
    il: "Niğde",
    eposta: "nigdesehir@saglik.gov.tr",
  },
  {
    id: "alici-ordu",
    ad: "Ordu Şehir Hastanesi",
    il: "Ordu",
    eposta: "ordusehir@saglik.gov.tr",
  },
  {
    id: "alici-rize",
    ad: "Rize Şehir Hastanesi",
    il: "Rize",
    eposta: "rizesehir@saglik.gov.tr",
  },
    {
    id: "alici-sakarya",
    ad: "Sakarya Şehir Hastanesi",
    il: "Sakarya",
    eposta: "sakaryasehir@saglik.gov.tr",
  },
  {
    id: "alici-samsun",
    ad: "Samsun Şehir Hastanesi",
    il: "Samsun",
    eposta: "samsunsehir@saglik.gov.tr",
  },
  {
    id: "alici-siirt",
    ad: "Siirt Şehir Hastanesi",
    il: "Siirt",
    eposta: "siirtsehir@saglik.gov.tr",
  },
  {
    id: "alici-sinop",
    ad: "Sinop Şehir Hastanesi",
    il: "Sinop",
    eposta: "sinopsehir@saglik.gov.tr",
  },
  {
    id: "alici-sivas",
    ad: "Sivas Şehir Hastanesi",
    il: "Sivas",
    eposta: "sivassehir@saglik.gov.tr",
  },
  {
    id: "alici-tekirdag",
    ad: "Tekirdağ Şehir Hastanesi",
    il: "Tekirdağ",
    eposta: "tekirdagsehir@saglik.gov.tr",
  },
  {
    id: "alici-tokat",
    ad: "Tokat Şehir Hastanesi",
    il: "Tokat",
    eposta: "tokatsehir@saglik.gov.tr",
  },
  {
    id: "alici-trabzon",
    ad: "Trabzon Şehir Hastanesi",
    il: "Trabzon",
    eposta: "trabzonsehir@saglik.gov.tr",
  },
  {
    id: "alici-tunceli",
    ad: "Tunceli Şehir Hastanesi",
    il: "Tunceli",
    eposta: "tuncelisehir@saglik.gov.tr",
  },
  {
    id: "alici-sanliurfa",
    ad: "Şanlıurfa Şehir Hastanesi",
    il: "Şanlıurfa",
    eposta: "sanliurfasehir@saglik.gov.tr",
  },
  {
    id: "alici-usak",
    ad: "Uşak Şehir Hastanesi",
    il: "Uşak",
    eposta: "usaksehir@saglik.gov.tr",
  },
  {
    id: "alici-van",
    ad: "Van Şehir Hastanesi",
    il: "Van",
    eposta: "vansehir@saglik.gov.tr",
  },
  {
    id: "alici-yozgat",
    ad: "Yozgat Şehir Hastanesi",
    il: "Yozgat",
    eposta: "yozgatsehir@saglik.gov.tr",
  },
  {
    id: "alici-zonguldak",
    ad: "Zonguldak Şehir Hastanesi",
    il: "Zonguldak",
    eposta: "zonguldaksehir@saglik.gov.tr",
  },
  {
    id: "alici-aksaray",
    ad: "Aksaray Şehir Hastanesi",
    il: "Aksaray",
    eposta: "aksaraysehir@saglik.gov.tr",
  },
  {
    id: "alici-bayburt",
    ad: "Bayburt Şehir Hastanesi",
    il: "Bayburt",
    eposta: "bayburtsehir@saglik.gov.tr",
  },
  {
    id: "alici-karaman",
    ad: "Karaman Şehir Hastanesi",
    il: "Karaman",
    eposta: "karamansehir@saglik.gov.tr",
  },
  {
    id: "alici-kirikkale",
    ad: "Kırıkkale Şehir Hastanesi",
    il: "Kırıkkale",
    eposta: "kirikkalesehir@saglik.gov.tr",
  },
  {
    id: "alici-batman",
    ad: "Batman Şehir Hastanesi",
    il: "Batman",
    eposta: "batmansehir@saglik.gov.tr",
  },
  {
    id: "alici-sirnak",
    ad: "Şırnak Şehir Hastanesi",
    il: "Şırnak",
    eposta: "sirnaksehir@saglik.gov.tr",
  },
  {
    id: "alici-bartin",
    ad: "Bartın Şehir Hastanesi",
    il: "Bartın",
    eposta: "bartinsehir@saglik.gov.tr",
  },
  {
    id: "alici-ardahan",
    ad: "Ardahan Şehir Hastanesi",
    il: "Ardahan",
    eposta: "ardahansehir@saglik.gov.tr",
  },
  {
    id: "alici-igdir",
    ad: "Iğdır Şehir Hastanesi",
    il: "Iğdır",
    eposta: "igdirsehir@saglik.gov.tr",
  },
  {
    id: "alici-yalova",
    ad: "Yalova Şehir Hastanesi",
    il: "Yalova",
    eposta: "yalovasehir@saglik.gov.tr",
  },
  {
    id: "alici-karabuk",
    ad: "Karabük Şehir Hastanesi",
    il: "Karabük",
    eposta: "karabuksehir@saglik.gov.tr",
  },
  {
    id: "alici-kilis",
    ad: "Kilis Şehir Hastanesi",
    il: "Kilis",
    eposta: "kilissehir@saglik.gov.tr",
  },
  {
    id: "alici-osmaniye",
    ad: "Osmaniye Şehir Hastanesi",
    il: "Osmaniye",
    eposta: "osmaniyesehir@saglik.gov.tr",
  },
  {
    id: "alici-duzce",
    ad: "Düzce Şehir Hastanesi",
    il: "Düzce",
    eposta: "duzcesehir@saglik.gov.tr",
  },
];

export const iller = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce",
];

export const tasimaAraclari = [
  "Frigorifik Araç - 34 AB 123",
  "Soğutmalı Kamyon - 25 CD 456",
  "Medikal Lojistik Aracı - 06 EF 789",
];

export const dashboardVerileri = {
  aktifSevkiyat: 28,
  tamamlananSevkiyat: 145,
  riskliSevkiyat: 3,
  bugunkuAlarm: 5,
  blockchainKayit: 1248,
};

export const aktifSevkiyatlar = [
  {
    id: "CC-0041",
    asiAdi: "Hepatit B",
    dozBilgisi: "500 Doz",
    aliciKurum: "Ankara Şehir Hast.",
    rota: "İstanbul -> Ankara",
    sonSicaklik: 4.2,
    durum: "Yolda",
    baslangicTarihi: "23.10.2023",
  },
  {
    id: "CC-0042",
    asiAdi: "Hepatit B",
    dozBilgisi: "500 Doz",
    aliciKurum: "Ankara Şehir Hast.",
    rota: "İstanbul -> Ankara",
    sonSicaklik: 4.2,
    durum: "Yolda",
    baslangicTarihi: "23.10.2023",
  },
];

export const alarmlar = [
  {
    id: "ALR-1001",
    alarm: "Yüksek Sıcaklık Limiti Aşıldı",
    sevkiyat: "VAC-001 (Hepatit B)",
    sicaklik: "9.4°C | Limit: 2-8°C",
    zaman: "15 dk önce",
    seviye: "Kritik",
  },
];

export const blockchainKayitlari = [
  {
    txId: "TX-1029",
    sevkiyatId: "VAC-2026-001",
    asi: "Hepatit B",
    islemTuru: "Sıcaklık İhlali",
    hash: "a8f3d92c1bfa8e91c204a7de7835f4a991ee2c47",
    tarih: "08.05.2026 14:32",
    durum: "Doğrulandı",
  },
];